spectrocloud/cluster-api-provider-aws

- Makefile
- prow/OWNERS
- prow/functions.sh
- prow/presubmit.sh
> test prow with 0.4 Makefile

- pkg/cloud/services/eks/roles.go
Fixes #
**Checklist**:
```release-note
```
> add ssm policy to eks nodegroup

- pkg/cloud/services/eks/fargate.go
- pkg/cloud/services/eks/tags.go
Fixes #
**Checklist**:
```release-note
```
> Fargate reconcile tags

- exp/controllers/awsmanagedmachinepool_controller.go
Fixes #
**Checklist**:
```release-note
```
> Force deletion

- exp/api/v1alpha3/awsfargateprofile_webhook.go
Allows update of additionalTags in AWSFargateProfile
Fixes #
**Checklist**:
```release-note
```
> allow update of additionalTags in AWSFargateProfile

- pkg/cloud/services/ec2/ami.go
Fixes #
**Checklist**:
```release-note
```
> add bastion ami to af-south-1 region

- cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_default_roles.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_awsmanagedmachinepools.yaml
- exp/api/v1alpha3/awsmanagedmachinepool_types.go
- exp/api/v1alpha3/zz_generated.deepcopy.go
- exp/controllers/awsmanagedmachinepool_controller.go
- main.go
- pkg/cloud/scope/managednodegroup.go
- pkg/cloud/services/eks/roles.go
- pkg/eks/identity_provider/plan_test.go
Fixes #
**Checklist**:
```release-note
```
> eks: support ng role additional policies

- exp/api/v1alpha3/awsmanagedmachinepool_types.go
- exp/api/v1alpha3/zz_generated.deepcopy.go
- pkg/cloud/services/eks/roles.go
Fixes #
**Checklist**:
```release-note
```
> update type for mmp role additional policies

- controlplane/eks/controllers/awsmanagedcontrolplane_controller.go
- pkg/cloud/services/securitygroup/securitygroups.go
Fixes #
**Checklist**:
```release-note
```
> disable bastion sg when bastion is disabled

- pkg/cloud/services/eks/cluster.go
- pkg/cloud/services/eks/cluster_test.go
Fixes #
**Checklist**:
```release-note
```
> add default cidr 0.0.0.0/0 as publicAccessCidr if nothing provided

- exp/api/v1alpha4/awsfargateprofile_webhook.go
Fixes #
**Checklist**:
```release-note
```
> tmp disable rolename webhook for fargate

- exp/api/v1alpha4/awsfargateprofile_webhook.go
Fixes #
**Checklist**:
```release-note
```
> allow updating roleName in fargate, if not already configured

- pkg/cloud/services/eks/nodegroup.go
Fixes #
**Checklist**:
```release-note
```
> Added cluster autoscaler support to EKS

- pkg/cloud/services/eks/iam/iam.go
Fixes #
**Checklist**:
```release-note
```
> Fixed OIDC deletion issue for private EKS cluster

- pkg/cloud/services/eks/config.go
Upgrade: Issues with EKS Cluster post upgrade
Update user/secret API version to "client.authentication.k8s.io/v1beta1"
(for example:)
Verified on:
> PCP-259: Upgrade: Issues with EKS Cluster post upgrade

- docs/book/src/topics/eks/pod-networking.md
- pkg/cloud/services/awsnode/cni.go
- pkg/cloud/services/awsnode/cni_test.go
> remove default eni env config

- main.go
removing second enableGates call which slipped in via a merge conflict.
> remove second enableGates Call

- pkg/cloud/services/eks/identity_provider.go
the idp provider was patching the object on every reconcile loop. this eliminates the patch if no status/arn was changed
> update idp reconciler to get out sooner if nothing to do

- Makefile
- pkg/cloud/services/eks/oidc.go
> Fixed trust policy reconcile issue

- cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_controller.go
> remove hardcoded partitions

- pkg/cloud/services/eks/roles.go
> Update arn for AmazonEKSClusterPolicy

- pkg/cloud/services/network/subnets.go
**What type of PR is this?** /kind bug
Fixing AWS Subnet Tags issue where tags are not getting deleted/updated on static placement cluster deletion
Fixes # PCP-230
**Checklist**:
> PCP-230: Fix AWS Cluster Tags Deletion & Re-addition issue

- controllers/awsmachine_controller_test.go
- pkg/cloud/services/ec2/instances.go
- pkg/cloud/services/ec2/instances_test.go
- pkg/cloud/services/network/subnets.go
> PCP-124: Adding tags to AWS Network Interfaces

- pkg/cloud/services/eks/nodegroup.go
> Fix providerIDList in managed node pools

- pkg/cloud/services/eks/nodegroup.go
> EKS: minSize and maxSize updates

- pkg/cloud/converters/tags.go
- pkg/cloud/services/eks/iam/iam.go
- pkg/cloud/services/eks/oidc.go
> PCP-732: Adding tags to OIDC providers

- Dockerfile
> Bumped golang to 1.20.2

- Dockerfile
> PSS-121: Update go in Dockerfile

- Dockerfile
> [rel] PSS-121: Update go in Dockerfile

- pkg/cloud/services/iam/iam.go
merging per approval https://github.com/spectrocloud/cluster-api-provider-aws/pull/699
> change to s3.<region>.amazonaws.com dns

- pkg/cloud/services/network/vpc.go
> [rel] PCP-1027: Remove continuously popping set attribute event

- .github/workflows/spectro-release.yaml
- Dockerfile
- Makefile
Integrate CICD into Cluster-API
Enable Versioning
Tag Syntax: v1.3.2-spectro-${SPECTRO_VERSION}
Enable FIPS based compile
To compile Fips images
export FIPS_ENABLE=yes
Fixes #
**Checklist**:
> Spectro CICD

- pkg/cloud/services/iam/oidc.go
> adding patches to join config

- .github/workflows/spectro-release.yaml
- Dockerfile
- Makefile
> Fix GH workflow

- .github/workflows/spectro-release.yaml
- Dockerfile
Forward Merge to Main Branch
========================
Fix Static Linking issue in FIPS builds
Fix version tag in Github Action from spectro-vx.x.x to vx.x.x-spectro to make sure Semantic versioning is followed
> Fips changes for Static Linking

- pkg/cloud/services/eks/cluster.go
> PCP-1505: palette continuously updating EKS cluster endpoints

- main.go
> PEM-2613: Update cipher suit

- main.go
> [rel] PEM-2613: Update cipher suit

- main.go
- util/flags/tls_boring.go
- util/flags/tls_non_boring.go
> PCP-1654: CAPA Cipher suit add boringcrypto flag for Max version

- main.go
- util/flags/tls_boring.go
- util/flags/tls_non_boring.go
> [rel] PCP-1654: CAPA Cipher suit add boringcrypto flag for Max version

- pkg/cloud/services/iam/iam.go
- pkg/cloud/services/s3/s3.go
- pkg/utils/resolver_endpoint.go
Fixes #
Logs:
```I0818 14:51:40.513621       1 s3.go:267]  "msg"="accessBucketFromDifferentRegion " "AWSCluster"={"name":"am-cluster-v1beta1-1-5-2","namespace":"am-cluster-v1beta1-1-5-2"} "bucket: "="am-aws-irsa" "cluster"="am-cluster-v1beta1-1-5-2" "controller"="awscluster" "controllerGroup"="infrastructure.cluster.x-k8s.io" "controllerKind"="AWSCluster" "name"="am-cluster-v1beta1-1-5-2" "namespace"="am-cluster-v1beta1-1-5-2" "reconcileID"="a7d2e2fb-4a43-4cf2-8c87-311addd8953a" "region: "="ap-south-1"
I0818 14:51:40.629926       1 s3.go:213]  "msg"="Deleting object" …
```
> PCP-1190: AWS with irsa configuration Cluster stuck in deletion

- pkg/cloud/scope/session.go
- pkg/utils/resolver_endpoint.go
- pkg/utils/resolver_endpoint_test.go
> PCP-1428: AWS CAPA changes to consume AWS FIPS endpoints

- pkg/cloud/scope/session.go
- pkg/cloud/services/s3/s3.go
- pkg/utils/resolver_endpoint.go
- pkg/utils/resolver_endpoint_test.go
> Pcp 1190 spectrov1

- Makefile
Testing ARM Build for Cluster API AWS
> Try Arm Build

- Dockerfile
- Makefile
/kind cleanup
Change builder args to have the version provided from Makefile
Include arm build
Test out Github actions to see if all three images are created 
**Checklist**:
> Sync with 4.0

- .github/workflows/spectro-release.yaml
- Dockerfile
- Makefile
Backport Github Action changes to 4.0 release branch from 4.1 release branch
> Backport GH Action changes

- pkg/cloud/services/iam/iam.go
> PCP-2076: AWS IRSA: s3 bucket incorrect URL

- pkg/cloud/services/iam/podidentitywebhook.go
- pkg/cloud/services/iam/reconcilers.go
This reverts commit 79167735dab525c96bd74b6e6faafdefd7c9355b.
and delete release: https://github.com/spectrocloud/cluster-api-provider-aws/releases/tag/v4.1.3-spectro 
Fixes #
**Checklist**:
> Revert "PCP-2154 (#867)"

- .backportrc.json
- .github/workflows/backport.yaml
Signed-off-by: Nianyu Shen <nianyu@spectrocloud.com>
Fixes #
**Checklist**:
> chore: add github backport action

- pkg/cloud/services/eks/oidc.go
> handle nil annotation

- go.mod
- go.sum
> PCP-3112: CVE-2024-24790 Fix
